Add deployment slots

diff --git a/.github/workflows/cicd-app-service.yml b/.github/workflows/cicd-app-service.yml
--- a/.github/workflows/cicd-app-service.yml
+++ b/.github/workflows/cicd-app-service.yml
@@ -87,9 +87,14 @@ jobs:
         run: |
           az webapp config set -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_APP_NAME}} --generic-configurations '{"healthCheckPath": ""}'
       
+      - name: Create a STAGING slot
+        run: |
+          az webapp deployment slot create -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_APP_NAME}} --slot staging --configuration-source ${{secrets.AZURE_APP_NAME}}
+          az webapp identity assign -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_APP_NAME}} --slot staging --identities "[system]"
+
       # Sometimes it helps to use the following - as azure/webapps-deploy@v2 output may be a bit confusing at times
       - name: Deploy to AppService
-        run: az webapp deploy -g ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_APP_NAME}} --type jar --src-path ./${{needs.build_app.outputs.RELEASE_FILE_NAME}}
+        run: az webapp deploy -g ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_APP_NAME}} --slot staging --type jar --src-path ./${{needs.build_app.outputs.RELEASE_FILE_NAME}}
       
       - name: Wait for AppService warm-up
         run: |
@@ -97,7 +102,7 @@ jobs:
           echo "Starting the warm-up wait: ${currentDateTime}"
           sleep 240 #First wait for 4 mins, sometimes it may take time for the deployment process to start
           noOfAttempts=0
-          until $(curl --silent --output /dev/null --head --fail https://${{secrets.AZURE_APP_NAME}}.azurewebsites.net/actuator/health/readiness); do
+          until $(curl --silent --output /dev/null --head --fail https://${{secrets.AZURE_APP_NAME}}-staging.azurewebsites.net/actuator/health/readiness); do
             if [[ ${noOfAttempts} -eq 60 ]];then
               echo "Web site failed to come online within 10 mins"
               exit 1
@@ -125,6 +130,36 @@ jobs:
 
       - name: Run integration test(s)
         run: |
-          echo "Run integration tests...."
+          status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "https://${{secrets.AZURE_APP_NAME}}-staging.azurewebsites.net/api/todos/")
+          if [[ "$status_code" -ne '200' ]] ; then
+            echo "Integration tests have failed"
+            exit 1
+          fi
 
-  
+      - name: Swap deployment and production slots
+        run: |
+          az webapp deployment slot swap -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_APP_NAME}} --slot staging --target-slot production
+
+      - name: Check the new production has warm-up
+        run: |
+          currentDateTime=`date`
+          echo "Production: starting the warm-up wait: ${currentDateTime}"
+          sleep 240 #First wait for 4 mins, sometimes it may take time for the swap process to finish (unless warm up optimization has been done)
+          noOfAttempts=0
+          until $(curl --silent --output /dev/null --head --fail https://${{secrets.AZURE_APP_NAME}}.azurewebsites.net/actuator/health/readiness); do
+            if [[ ${noOfAttempts} -eq 60 ]];then
+              echo "Web site failed to come online within 10 mins"
+              exit 1
+            fi
+            noOfAttempts=$(($noOfAttempts+1))
+            sleep 10
+          done
+          currentDateTime=`date`
+          echo "Production: finnished the warm-up wait: ${currentDateTime}"
+          echo "Production: service warmed up after ${noOfAttempts} attempts"
+        
+      # - name: Remove deployment slots
+      #   run: |
+      #     az webapp deployment slot delete --slot deployment --b ${{secrets.AZURE_APP_NAME}} -g ${{secrets.AZURE_RESOURCE_GROUP}}
+      #     echo "Run integration tests...."
+
