test

diff --git a/.github/workflows/cicd-app-service-infra.yml b/.github/workflows/cicd-app-service-infra.yml
--- a/.github/workflows/cicd-app-service-infra.yml
+++ b/.github/workflows/cicd-app-service-infra.yml
@@ -184,10 +184,20 @@ jobs:
           echo "App service name: '${{secrets.AZURE_APP_NAME}}'"
           echo "App port: '${{secrets.AZURE_APP_PORT}}'"
 
-          az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi-init.bicep \
-                        --parameters location=${{secrets.AZURE_LOCATION}}  \
-                                     appServiceName=${{secrets.AZURE_APP_NAME}} \
-                                     appServicePort=${{secrets.AZURE_APP_PORT}}
+          if [[ "${{github.event.inputs.deployment_environment}}" == 'MANAGED_IDENTITIES' ]]; then
+            az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi-init.bicep \
+                          --parameters location=${{secrets.AZURE_LOCATION}}  \
+                                      appServiceName=${{secrets.AZURE_APP_NAME}} \
+                                      appServicePort=${{secrets.AZURE_APP_PORT}}
+          elif [[ "${{github.event.inputs.deployment_environment}}" == 'VNET' ]]; then
+            az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi-vnet-init.bicep \
+                          --parameters location=${{secrets.AZURE_LOCATION}}  \
+                                       appServiceName=${{secrets.AZURE_APP_NAME}} \
+                                       appServicePort=${{secrets.AZURE_APP_PORT}}
+          else
+            echo "Invalid option"
+            exit 1
+          fi
 
       - name: Deploy Azure resources (AAD Integration)
         id: deployment_aad
@@ -196,21 +206,39 @@ jobs:
           dbAppUserId=`az ad sp list --display-name "${{secrets.AZURE_APP_NAME}}" --query "[?displayName=='${{secrets.AZURE_APP_NAME}}'].appId" --out tsv`
           echo "::set-output name=DB_APP_USER_ID::${dbAppUserId}"
 
-          az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi.bicep \
-                        --parameters location=${{secrets.AZURE_LOCATION}}  \
-                                     logAnalyticsWorkspaceName=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_NAME}}  \
-                                     logAnalyticsWorkspaceRG=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_RESOURCE_GROUP}} \
-                                     keyVaultName=${{secrets.AZURE_KEY_VAULT_NAME}}  \
-                                     appInsightsName=${{secrets.AZURE_APP_INSIGHTS_NAME}}  \
-                                     dbServerName=${{secrets.AZURE_DB_SERVER_NAME}} \
-                                     dbName=${{secrets.AZURE_DB_NAME}} \
-                                     createDB=${{steps.vars.outputs.DB_NOT_INITIALIZED}} \
-                                     dbAdminName=${{steps.vars.outputs.DB_ADMIN_NAME}} \
-                                     dbAdminPassword=${{steps.vars.outputs.DB_ADMIN_PASSWORD}} \
-                                     dbUserName=${{steps.vars.outputs.DB_APP_USER_NAME}}@${{secrets.AZURE_DB_SERVER_NAME}} \
-                                     appServiceName=${{secrets.AZURE_APP_NAME}} \
-                                     appServicePort=${{secrets.AZURE_APP_PORT}} \
-                                     deploymentClientIPAddress=${{steps.vars.outputs.DEPLOYMENT_CLIENT_IP}}
+          if [[ "${{github.event.inputs.deployment_environment}}" == 'MANAGED_IDENTITIES' ]]; then
+            az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi.bicep \
+                          --parameters location=${{secrets.AZURE_LOCATION}}  \
+                                       logAnalyticsWorkspaceName=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_NAME}}  \
+                                       logAnalyticsWorkspaceRG=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_RESOURCE_GROUP}} \
+                                       keyVaultName=${{secrets.AZURE_KEY_VAULT_NAME}}  \
+                                       appInsightsName=${{secrets.AZURE_APP_INSIGHTS_NAME}}  \
+                                       dbServerName=${{secrets.AZURE_DB_SERVER_NAME}} \
+                                       dbName=${{secrets.AZURE_DB_NAME}} \
+                                       createDB=${{steps.vars.outputs.DB_NOT_INITIALIZED}} \
+                                       dbAdminName=${{steps.vars.outputs.DB_ADMIN_NAME}} \
+                                       dbAdminPassword=${{steps.vars.outputs.DB_ADMIN_PASSWORD}} \
+                                       dbUserName=${{steps.vars.outputs.DB_APP_USER_NAME}}@${{secrets.AZURE_DB_SERVER_NAME}} \
+                                       appServiceName=${{secrets.AZURE_APP_NAME}} \
+                                       appServicePort=${{secrets.AZURE_APP_PORT}} \
+                                       deploymentClientIPAddress=${{steps.vars.outputs.DEPLOYMENT_CLIENT_IP}}
+          else
+            az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./templates/app-service-mi-vnet.bicep \
+                          --parameters location=${{secrets.AZURE_LOCATION}}  \
+                                       logAnalyticsWorkspaceName=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_NAME}}  \
+                                       logAnalyticsWorkspaceRG=${{secrets.AZURE_LOG_ANALYTICS_WRKSPC_RESOURCE_GROUP}} \
+                                       keyVaultName=${{secrets.AZURE_KEY_VAULT_NAME}}  \
+                                       appInsightsName=${{secrets.AZURE_APP_INSIGHTS_NAME}}  \
+                                       dbServerName=${{secrets.AZURE_DB_SERVER_NAME}} \
+                                       dbName=${{secrets.AZURE_DB_NAME}} \
+                                       createDB=${{steps.vars.outputs.DB_NOT_INITIALIZED}} \
+                                       dbAdminName=${{steps.vars.outputs.DB_ADMIN_NAME}} \
+                                       dbAdminPassword=${{steps.vars.outputs.DB_ADMIN_PASSWORD}} \
+                                       dbUserName=${{steps.vars.outputs.DB_APP_USER_NAME}}@${{secrets.AZURE_DB_SERVER_NAME}} \
+                                       appServiceName=${{secrets.AZURE_APP_NAME}} \
+                                       appServicePort=${{secrets.AZURE_APP_PORT}} \
+                                       deploymentClientIPAddress=${{steps.vars.outputs.DEPLOYMENT_CLIENT_IP}}
+          fi
           cd ..
 
       - name: Deploy Azure resources (NO AAD Integration)
