add warm-up

diff --git a/.github/workflows/cicd-app-service.yml b/.github/workflows/cicd-app-service.yml
--- a/.github/workflows/cicd-app-service.yml
+++ b/.github/workflows/cicd-app-service.yml
@@ -83,10 +83,22 @@ jobs:
       - name: Set default Azure subscription
         run: az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
-      # Sometimes it helps to use the following - as azure/webapps-deploy@v2 are a bit confusing
+      # Sometimes it helps to use the following - as azure/webapps-deploy@v2 output may be a bit confusing at times
       - name: Deploy to AppService
         run: az webapp deploy -g ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_APP_NAME}} --type jar --src-path ./${{needs.build_app.outputs.RELEASE_FILE_NAME}}
       
+      - name: Wait for AppService warm-up
+        run: |
+          noOfAttempts=0
+          until $(curl --silent --output /dev/null --head --fail https://${{secrets.AZURE_APP_NAME}}.azurewebsites.net/actuator/health/readiness); do
+          https://mabr-tiny-java-as
+            if [[ ${noOfAttempts} -eq 60 ]];then
+              echo "Web site failed to come online within 10 mins"
+              exit 1
+            fi
+            noOfAttempts=$(($noOfAttempts+1))
+            sleep 10
+          done
       # - name: Deploy to AppService
       #   uses: azure/webapps-deploy@v2
       #   with: 
