Update cicd-spring-apps.yml

diff --git a/.github/workflows/cicd-spring-apps.yml b/.github/workflows/cicd-spring-apps.yml
--- a/.github/workflows/cicd-spring-apps.yml
+++ b/.github/workflows/cicd-spring-apps.yml
@@ -1,4 +1,4 @@
-name: cicd-app-spring-apps
+name: cicd-spring-apps
 
 on:
   #push:
@@ -36,36 +36,40 @@ jobs:
       #         run mvwm and init it from java spring-boot on the admin connection (?)
       - name: Initialize database
         run: |
+          dbAdminPassword="`openssl rand -hex 25`#@"
+          echo "::add-mask::$dbAdminPassword"
+          dbAdminName=""
+          dbServerName="${{secrets.AZURE_DB_SERVER_NAME}}"
+          pgsqlServerAdminQuery="[?fullyQualifiedDomainName == '${dbServerName}.postgres.database.azure.com'].administratorLogin"
+          dbAdminName=`az postgres server list --query "$pgsqlServerAdminQuery" -o tsv`
+          if [[ -z $dbAdminName ]]; then
+            error "Unable to retrieve admin name"
+            exit 1;
+          fi
+          az postgres server update --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_DB_SERVER_NAME }} --admin-password $dbAdminPassword
+          
+          dbConnectionStringTodoDB="host=${{ secrets.AZURE_DB_SERVER_NAME }}.postgres.database.azure.com port=5432 dbname=${{ secrets.AZURE_DB_NAME }} user=${dbAdminName} password=${dbAdminPassword} sslmode=require"
+          dbConnectionStringPostgresDB="host=${{ secrets.AZURE_DB_SERVER_NAME }}.postgres.database.azure.com port=5432 dbname=postgres user=${dbAdminName} password=${dbAdminPassword} sslmode=require"
               
-              pgsqlServerAdminQuery="[?fullyQualifiedDomainName == '${{secrets.AZURE_DB_SERVER_NAME}}.postgres.database.azure.com'].administratorLogin"
-
-              $dbAdminName=`az postgres server list --query "$pgsqlServerAdminQuery" --output tsv`
-              $dbAdminPassword="#`openssl rand -base64 25`#"
-
-              az postgres server update --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_DB_SERVER_NAME }} --admin-password $dbAdminPassword
-
-              dbConnectionStringTodoDB="host=${{ secrets.AZURE_DB_SERVER_NAME }}.postgres.database.azure.com port=5432 dbname=${{ secrets.AZURE_DB_NAME }} user=$dbAdminName password=\"$dbAdminPassword\" sslmode=require"
-              dbConnectionStringPostgresDB="host=${{ secrets.AZURE_DB_SERVER_NAME }}.postgres.database.azure.com port=5432 dbname=postgres user=$dbAdminName password=\"$dbAdminPassword\" sslmode=require"
+          psql "${dbConnectionStringTodoDB}" --file=./db.sql
               
-              psql "${dbConnectionStringTodoDB}" --file=./db.sql
-              
-              dbUserName="${{secrets.AZURE_API_DB_USER_NAME}}"
-              dbUserPassword="${{secrets.AZURE_API_DB_USER_PASSWORD}}"
+          dbUserName="${{secrets.AZURE_API_DB_USER_NAME}}"
+          dbUserPassword="${{secrets.AZURE_API_DB_USER_PASSWORD}}"
 
-              dbUserExists=`psql "${dbConnectionStringPostgresDB}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$dbUserName';"`
+          dbUserExists=`psql "${dbConnectionStringPostgresDB}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$dbUserName';"`
 
-              if [[ $dbUserExists -ne '1' ]]; then
-                echo "...creating the user"
-                psql "${dbConnectionStringPostgresDB}" -tAc "CREATE USER $dbUserName WITH PASSWORD '$dbUserPassword';"
-              else
-                echo "...re-setting the password"
-                psql "${dbConnectionStringPostgresDB}" -tAc "ALTER USER $dbUserName WITH PASSWORD '$dbUserPassword';"
-              fi
-              echo "Granting user access"
-              psql "${dbConnectionStringPostgresDB}" -tAc "GRANT CONNECT ON DATABASE ${{ secrets.AZURE_DB_NAME }} TO $dbUserName;"
-              psql "${dbConnectionStringTodoDB}" -tAc "GRANT USAGE ON SCHEMA public TO $dbUserName;"
-              psql "${dbConnectionStringTodoDB}" -tAc "GRANT SELECT ON todo TO $dbUserName;"
-              psql "${dbConnectionStringTodoDB}" -tAc "GRANT INSERT ON todo TO $dbUserName;"              
+          if [[ $dbUserExists -ne '1' ]]; then
+            echo "...creating the user"
+            psql "${dbConnectionStringPostgresDB}" -tAc "CREATE USER $dbUserName WITH PASSWORD '$dbUserPassword';"
+          else
+            echo "...re-setting the password"
+            psql "${dbConnectionStringPostgresDB}" -tAc "ALTER USER $dbUserName WITH PASSWORD '$dbUserPassword';"
+          fi
+          echo "Granting user access"
+          psql "${dbConnectionStringPostgresDB}" -tAc "GRANT CONNECT ON DATABASE ${{ secrets.AZURE_DB_NAME }} TO $dbUserName;"
+          psql "${dbConnectionStringTodoDB}" -tAc "GRANT USAGE ON SCHEMA public TO $dbUserName;"
+          psql "${dbConnectionStringTodoDB}" -tAc "GRANT SELECT ON todo TO $dbUserName;"
+          psql "${dbConnectionStringTodoDB}" -tAc "GRANT INSERT ON todo TO $dbUserName;"              
 
   build_app:
     runs-on: ubuntu-latest
@@ -113,23 +117,23 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: ${{ steps.version.outputs.RELEASE_NAME }}
-          path: ./todo/target/${{ steps.version.outputs.RELEASE_FILE_NAME }}
+          path: ./api/target/${{ steps.version.outputs.RELEASE_FILE_NAME }}
           if-no-files-found: error
           retention-days: 1
   
   deploy_app:
-    needs: [build_app, init_db]
+    needs: [build_api, init_db]
     runs-on: ubuntu-latest
     steps:
       - name: Download build artefacts
         uses: actions/download-artifact@v2
         with:
-          name: ${{needs.build_app.outputs.RELEASE_NAME}}
+          name: ${{needs.build_api.outputs.RELEASE_NAME}}
       - name: Check downloaded files
         run: |
           pwd
           ls -la
-          ls -la ./${{ needs.build_app.outputs.RELEASE_FILE_NAME }}
+          ls -la ./${{ needs.build_api.outputs.RELEASE_FILE_NAME }}
       
       - name: Azure login
         uses: azure/login@v1
@@ -141,6 +145,12 @@ jobs:
       - name: Set default Azure subscription
         run: az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
+      - name: Deploy to AppService
+        uses: azure/webapps-deploy@v2
+        with: 
+          app-name: "${{ secrets.AZURE_API_SERVICE_NAME }}"
+          package: ./${{ needs.build_api.outputs.RELEASE_FILE_NAME }}
+      
       - name: Deploy to Spring Apps
         uses: azure/spring-cloud-deploy@v1
         with:
@@ -151,7 +161,6 @@ jobs:
           use-staging-deployment: false
           package: ./todo/target/**/*.jar
 
-      
       - name: Run integration test(s)
         run: |
           echo "Run integration tests...."
